services:
  pgduckdb:
    image: pgduckdb/pgduckdb:18-main
    container_name: pgduckdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgduckdb_data:/var/lib/postgresql
      - /mnt/d/lakehouse:/lakehouse:rw  # Добавляем монтирование для DuckDB
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 0"]  # Более мягкий healthcheck
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

# MS SQL Server 2022
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - /mnt/d/lakehouse:/lakehouse:rw  # Общая папка для данных
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P \"$$MSSQL_SA_PASSWORD\" -Q \"SELECT 1\" || exit 0"]  # <-- ИСПРАВЛЕНО
      #test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P mssql123@Pwd -Q \"SELECT 1\" || exit 0"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

# Analytical Engine
  duckdb:
    image: duckdb/duckdb:latest
    volumes:
      - ./lakehouse:/lakehouse_local:rw
      - /mnt/d/lakehouse:/lakehouse:rw     # Внешняя папка
      - ./scripts:/scripts
    working_dir: /lakehouse
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          memory: 6G  # Увеличиваем лимит памяти
        reservations:
          memory: 4G

  dbt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dbt-pgduckdb
    ports:
      - "8080:8080"
    volumes:
      - ./dbt_project:/usr/app
    working_dir: /usr/app
    environment:
      DBT_PROFILES_DIR: /usr/app
      DATABASE_URL: "postgresql://postgres:${PG_PASSWORD}@pgduckdb:5432/postgres"
      PG_PASSWORD: ${PG_PASSWORD}  # <-- Передаем переменную в контейнер
    depends_on:
      - pgduckdb
    entrypoint: ["/bin/sh", "-c"]  # Переопределяем entrypoint
    command: ["sleep infinity"]    # Теперь sleep будет выполняться через shell

volumes:
  pgduckdb_data:
  mssql_data:
